---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart xray xhttp
  systemd:
    name: xray-xhttp
    state: restarted
    daemon_reload: yes

- name: reload nginx xhttp
  systemd:
    name: nginx
    state: reloaded
